[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "slickpy"
dynamic = ["version"]
description = "A lightweight ASGI toolkit, optimized for great performance, flexibility and productivity."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [{ name = "Andriy Kornatskyy", email = "andriy.kornatskyy@live.com" }]
keywords = ["ASGI", "http", "web", "toolkit"]
classifiers = [
  "Development Status :: 1 - Planning",
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
  "Topic :: Software Development :: Libraries :: Application Frameworks",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
Homepage = "https://github.com/akornatskyy/slickpy"

[tool.setuptools]
packages = ["slickpy", "slickpy.experimental", "slickpy.middleware"]
package-dir = { "" = "src" }
zip-safe = true
include-package-data = true
platforms = ["any"]

[tool.setuptools.package-data]
slickpy = ["py.typed"]

[tool.setuptools.dynamic]
version = { attr = "slickpy.__version__" }

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.coverage.run]
source = ["src/slickpy"]
omit = ["*/test_*.py", "*/tests/*"]
